// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbyxE9D-hiSCIV6rGVukGEUsVxQYltU4M',
    appId: '1:519089750333:web:2e2442b4dd14ce9ab14554',
    messagingSenderId: '519089750333',
    projectId: 'fix-my-car-e690c',
    authDomain: 'fix-my-car-e690c.firebaseapp.com',
    storageBucket: 'fix-my-car-e690c.firebasestorage.app',
    measurementId: 'G-L1JF7TG2WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxvXBecScBDqmCB2VeU7rvI2sXk84K24Q',
    appId: '1:519089750333:android:34d2e7c18d15695db14554',
    messagingSenderId: '519089750333',
    projectId: 'fix-my-car-e690c',
    storageBucket: 'fix-my-car-e690c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM93f69-aR0BW9oOa6uvbr9NrckGFlHx0',
    appId: '1:519089750333:ios:e52ffb30e6743798b14554',
    messagingSenderId: '519089750333',
    projectId: 'fix-my-car-e690c',
    storageBucket: 'fix-my-car-e690c.firebasestorage.app',
    iosBundleId: 'com.example.tawselFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM93f69-aR0BW9oOa6uvbr9NrckGFlHx0',
    appId: '1:519089750333:ios:e52ffb30e6743798b14554',
    messagingSenderId: '519089750333',
    projectId: 'fix-my-car-e690c',
    storageBucket: 'fix-my-car-e690c.firebasestorage.app',
    iosBundleId: 'com.example.tawselFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbyxE9D-hiSCIV6rGVukGEUsVxQYltU4M',
    appId: '1:519089750333:web:efad6413506eb53bb14554',
    messagingSenderId: '519089750333',
    projectId: 'fix-my-car-e690c',
    authDomain: 'fix-my-car-e690c.firebaseapp.com',
    storageBucket: 'fix-my-car-e690c.firebasestorage.app',
    measurementId: 'G-QBKC281PVL',
  );

}